// Explicit list of all handlers so they are compiled by ncc.
require('./go/go')
require('./java/gradle')
require('./java/maven')
require('./node/npm')
require('./node/yarn')
require('./php/composer')
require('./python/pip')
require('./r/renv')
require('./ruby/bundler')
require('./rust/cargo')
require('./scala/sbt')
require('./swift/carthage')
require('./swift/cocoapods')
require('./swift/spm')