name: AWS Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: AWS cache
        uses: ./
        with:
          type: npm
          provider: aws
        env: 
          AWS_BUCKET_NAME: ${{secrets.BUCKET_NAME}}
      - name: Install dependencies
        run: |
          npm ci


