name: AWS Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-aws:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: AWS cache
        uses: ./
        with:
          type: npm
          provider: aws
        env: 
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${secrets.ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${secrets.SECRET_ACCESS_KEY}
          AWS_BUCKET_NAME: ${secrets.BUCKET_NAME}
      - name: Install dependencies
        run: |
          npm ci


