name: Local Provider Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-local-native:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Local cache
        uses: ./
        with:
          type: npm
          provider: local
      - name: Install dependencies
        run: |
          npm ci

  test-local-no-native:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Local cache
        uses: ./
        with:
          type: npm
          provider: local
        env:
          CACHE_DISABLE_NATIVE: 'true'
      - name: Install dependencies
        run: |
          npm ci

