name: Local Provider Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test-local-provider:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Local cache
        uses: ./
        with:
          type: npm
          provider: local
      - name: Install dependencies
        run: |
          npm ci


